nelmio_api_doc:
    documentation:
        servers:
            -   url: http://twouiter.fr/doc
                description: Twouiter API
        info:
            title: Twouiter API
            description: A legit fork from Twitter, trust me
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: [ ]

    areas: # to filter documented areas
        path_patterns: # an array of regexps (document only routes under /api, except /api/doc)
            - ^/api(?!/(doc|doc\.json)$)
        #host_patterns: # document only routes with a host of the form api.*
        #    - ^api\.
